# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dasan/Desktop/ECE385FinalProject/ece_385_final_vivado/ece_385_final_vivado.srcs/sources_1/ip/LVL_1_rom/LVL_1_rom.xci
# IP: The module: 'LVL_1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dasan/Desktop/ECE385FinalProject/ece_385_final_vivado/ece_385_final_vivado.gen/sources_1/ip/LVL_1_rom/LVL_1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LVL_1_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/dasan/Desktop/ECE385FinalProject/ece_385_final_vivado/ece_385_final_vivado.srcs/sources_1/ip/LVL_1_rom/LVL_1_rom.xci
# IP: The module: 'LVL_1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dasan/Desktop/ECE385FinalProject/ece_385_final_vivado/ece_385_final_vivado.gen/sources_1/ip/LVL_1_rom/LVL_1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LVL_1_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
